- examples/basic.rs
- src/lib.rs
This is a bit more verbose, and I am open to alternatives.
The `WorldArgs` from before was a bit implicit in when the next system was triggered to go. It was triggered off of access to `entities`. This caused issue for me when the first thing I tried was a call that did not use this api.
> add a fetch function to the WorldArgs

- src/lib.rs
- src/storage.rs
VecStorage::sub would panic if you delete an out of generation id.
Add tests to make sure the behavior of vec/hashmap is consistent.
> add some tests!

- src/lib.rs
- src/storage.rs
@csherratt you were asking for it, yet used the old add/sub extensively in the tests. I wonder if there is a reason to stay with the old names.
> Renamed add/sub to insert/remove

- src/lib.rs
- src/world.rs
Use a barrier to stall the scheduler when wait is called.
> actully wait

- src/storage.rs
- src/world.rs
- tests/tests.rs
Using the length of generations is not a reliable source of the
next entity as it is out of date when using dynamic entity creation
> Fix entity reuse using dynamic create.

- src/lib.rs
- src/storage.rs
- src/world.rs
Instead, expose `is_alive()` and `is_dead()` methods which have a clear
name, and refactor existing code to use these.
> Hide implementation of Generation

- src/world.rs
- tests/tests.rs
Also fix a bug in `create_now()`, which would not update the stored
`Generation` in some cases.
Implements #34
> Add `World::is_alive(Entity)` method

- src/bitset.rs
- src/lib.rs
- src/storage.rs
- src/world.rs
Also turns all comments of the form `Return value x` into the form
`Returns value x`, which is in line with official rust docs.
> Cleanup documenation at many places.

- src/world.rs
`assert_eq!` also prints the values of the two sides in case of panic,
so `assert_eq!(a, b)` should be preferred over `assert!(a == b)`.
> replace two asserts with assert_eq!s

- examples/basic.rs
- src/bitset.rs
- src/join.rs
- src/lib.rs
- src/storage.rs
- src/world.rs
This is a follow-up to my changes that added the bitset masks. This gives a way for api users to do the bitset join in a much more friendly way then we were doing before.
Take a look at the updated example to see how it works.
> Add a `Join` trait

- Cargo.toml
- examples/basic.rs
- src/lib.rs
- tests/tests.rs
Closes #30 
The new code somehow introduces a deadlock in the tests. AFAIK, all I did was changing a pulse/barrier into a channel.
> Added the System trait

- examples/basic.rs
- src/bitset.rs
- src/join.rs
- src/lib.rs
- src/storage.rs
- src/world.rs
- tests/tests.rs
- The DynamicEntityIter is removed
- Allocation / Deletion can be done without a write lock
- Add the ability to `Join` over the `entities()`
This removes the `add_list/sub_list` in-favour of atomic bit sets. Killing an Entity sets a bit atomically that can be looked up later during the merge. Raising a dead entity is done via an atomic bitset too. This allows systems to iterate over the entities without blocking system that need to create or delete entities.
The other big part of this change is that the functionality of the DynamicEntityIter & the EntitiyIter are now in one place. We merge the known alive entity ids, with any raised entities. The `Entities` can see entities that are created by systems in parallel, which might cause some unpredictable behaviour. But if you are masking …
> [WIP] Refactor how allocation/deletion works

- examples/basic.rs
- src/bitset.rs
- src/join.rs
- src/lib.rs
- src/storage.rs
- src/world.rs
- tests/tests.rs
Fixes #32 
Major changes:
- `BitSet` is exposed directly
- `VecStorage` and `HashMapStorage` implementations are much simpler, all the shared logic is moved up to the `MaskedStorage` and `Storage` types
- `Storage` is no longer a trait but a struct, which allows using its methods without any `use` items
- Storages no longer track the generations internally, but instead use the shared generations from the `World`
- `join` module is cleaned up by half
Performance:
| Benchmark  | specs-0.5.1 | specs-master | specs-pr |
| --------------- | --------------- | ----------------- | ----------- |
| pos_vel build | 320 us/iter (+/- 8) | 2,013 us/iter (+/- 139) |1,940 us/iter (+/- 75) |
| pos_vel update | 42 us/iter (+/- 8) | 42 us/iter (+/- 9) |42 us/iter (+/- 11) |
| parallel build | 472 us/iter …
> Major Storage refactor

- src/lib.rs
- src/storage.rs
This makes the storage api closer to the rust api, and allows for a more efficient logging of changes. IE a changefeed that works on-top of the of specs.
This is an api breaking change.
> Return the old value during a insert.

- src/lib.rs
- src/world.rs
This is needed to write out the types in, eg, a struct.
> Exported all types need for the return types of World::read() and World::write()

- tests/tests.rs
This commit adds a **failing** test addressing dynamic creation and deletion of entities in different systems. The core intent is to check whether components can be inserted immediately after entity creation. Note that in a test which only creates entities (ie. without deleting any) I was not able to detect the problem this test is designed to highlight.
cc @kvark
> Test for stillborn entities

- src/world.rs
- tests/tests.rs
Issue: #64 
I added dynamic identifiers for the components in addition of the original type identifiers, while keeping the interface of `World` and `EntityBuilder` backwards compatible.
The both identifiers are equal, so that there can be multiple components with the same dynamic id but different type id.
(I also added a simple test case for the feature)
> Dynamic component type feature

- src/storage.rs
- src/world.rs
TypeId is a u64 in reality. C is usually ()
It may be desirable to make the hasher a type parameter
> World: use fnv

- src/storage.rs
as mentioned in the issue #73 the drain iterator doesn't iterate
correctly on this unsafe inserted vector.
I don't know if it is expected and I will post the question on forums soon.
this commit contains a test that failed in past and an
implementation that pass this test.
basically it cleans the vector like it fills it by swapping value to drop
them and then set it len to 0
closes #73
> debug free of vec storage

- src/bitset.rs
- src/join.rs
- src/planner.rs
- src/world.rs
Just some various spelling and grammar fixes to the documentation for consistency with other documentation.
> Documentation spelling/grammar fixes

- examples/basic.rs
- src/storage.rs
Somewhat similar to `AntiStorage`, allows iteration through entities that have components without returning the components in the iterator.
> CheckStorage

- src/planner.rs
Places all `impl_run!` macro invocations inside a single `impl` block.
The result is functionally identical, but makes the documentation more
readable.
> Cleanup `Planner::run*` implementations

- src/world.rs
- tests/tests.rs
Previously repeated calls to `register` (and friends) would stomp over
the existing storage for the component type.
Now repeated calls will silently do nothing.
> Make World::register* functions idempotent (#96)

- benches/benches.rs
- examples/basic.rs
- src/planner.rs
- src/world.rs
- tests/tests.rs
- rename `create_later_build` to `create`, assuming it's what users actually want to use
- rename `create_later` to `create_pure`, reflecting the fact only the Entity is created with no building.
Also rename `RunArg::create` to `RunArg::create_pure` for the same reason.
> Rename funcs according to #87

- benches/benches.rs
- src/lib.rs
I tried to run benchmarks and noticed that they don't work:
* bitsets were moved to different place, were private and didn't have documentations
* There were mutability problems with bunch of benchmarks.
After fixing these, benchmarks work, but `create_now` test panics:
````
test world::create_now              ... thread 'main' panicked at 'index out of bounds: the len is 1024 but the index is 1024', src\libcollections\vec.rs:1401
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
0: specs::world::Allocator::allocate
1: <specs::world::World<C>>::create_now
2: benches::world::create_now
3: test::run_test
4: test::run_tests
5: test::run_tests_console
6: test::test_main
7: test::test_main_static
8: benches::__test::main
9: …
```
> Made benchmarks runnable

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/storage.rs
- src/world.rs
The ticket feature was non-additive. This way, the library only provides a version with tickets.
I'll do some crate polishing after this is merged.
> Remove ticket feature

- src/lib.rs
- src/storage.rs
It was not exported even though it's part of the public API (I though there was an error for this).
* Add documentation
* Add cfg attribute
> Reexport MergeError

- examples/serialize.rs
In `examples/serialize` was an import for `std::fmt` which
is only needed for the `serialize` feature.
> Move std::fmt import into submodule

- examples/basic.rs
- src/storage.rs
`CheckStorage` will return an `Entry` which can be used to get components from a storage without the unnecessary checks.
> CheckStorage Entry

- src/storage.rs
- src/world.rs
Removes bounds on the struct, but leaving them in the implementations removes a lot of boilerplate when using the `World`. Since not all methods related to the `World` require those bounds.
> Remove bounds from world struct and entity builder

- src/storage/mod.rs
- src/world.rs
Just adds a getter to the `Generation` for getting the id.
Also changes the getters to follow the rust guidelines.
fixes #148
> Expose generation id/Follow rust guidelines for getters

- Cargo.toml
This temporarily locks the shred dependency on the current commit, so it does not break as soon as I merge anything into shred master.
> Use published hibitset and lock shred dependency

- src/join.rs
- src/storage/mod.rs
Anonymous function parameters are deprecated as of RFC 1685.
> Add parameter names to anonymous function parameters

- book/src/06_system_data.md
- examples/full.rs
- examples/serialize.rs
- src/lib.rs
- src/world.rs
I wonder if we should just always call `world.maintain()` in the examples.
> Better document that World::maintain is necessary after using `Entities`

- .travis.yml
- Cargo.toml
- bors.toml
This allows to use [bors-ng](https://github.com/bors-ng/bors-ng) GitHub application.
@kvark 
Tried it out for `shred`, seems to work fine.
> Setup bors integration

- Cargo.toml
- benches/parallel.rs
- book/src/02_hello_world.md
- src/lib.rs
- src/storage/mod.rs
Now specs can make use of [a major optimization](https://github.com/slide-rs/shred/pull/33) in `shred` and [a bugfix](https://github.com/slide-rs/shred/issues/35) in `shred-derive`.
Also improves bench by specifying running time.
> Update to shred 0.4

- src/lib.rs
- src/storage/mod.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world.rs
A basic implementation for a `TrackedStorage` (https://github.com/slide-rs/specs/issues/89).
This version of the `TrackedStorage` does not implement a way to compare the past version and the modifies version of the components. Usage requires unwrapping the storage to the base `TrackedStorage` which implements `Join` for flagged components.
**Implement `TrackedStorage` similar to how `MaskedStorage` works.**
_Pros:_
- Would make it possible to have the `Join` of the storage only work on the flagged components without calling any additional methods.
- Might open up a path for a generic storage wrapper like `UnprotectedStorage` but instead as a container for how the `Join` gets the components necessary for the loop (this could be interesting since it would allow for different methods other …
> FlaggedStorage

- src/join.rs
This allows to iterate over a single component storage in parallel.
r? @WaDelma
> Remove `Split` bound from parallel iterator impl

- benches/benches.rs
- examples/basic.rs
- src/lib.rs
- src/storage/mod.rs
- tests/tests.rs
* Note in basic example and crate root
* Reexport in crate root
* Add benchmark for them
```
test world::join_multi_threaded     ... bench:      77,374 ns/iter (+/- 20,560)
test world::join_single_threaded    ... bench:     233,356 ns/iter (+/- 2,279)
```
:tada:
> Add parallel joins to several places

- .rustfmt.toml
- README.md
- benches/parallel.rs
- benches/world.rs
- book/src/02_hello_world.md
- book/src/03_dispatcher.md
- book/src/04_resources.md
- book/src/05_storages.md
- book/src/06_system_data.md
- examples/basic.rs
- examples/full.rs
- examples/serialize.rs
- src/join.rs
- src/lib.rs
- src/storage/check.rs
- src/storage/data.rs
- src/storage/mod.rs
- src/storage/ser.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world.rs
- tests/tests.rs
* No crate root types, all grouped into modules
* `prelude` module reexports only `Join` and `ParJoin`
> Restructure type reexports

- Cargo.toml
This fixes a broken build because of reliance on unstalbe rayon features. Sorry for breaking your build.
Please upgrade to Specs 0.9.1.
Fixes #193
> Update to shred 0.4.2 and hibitset 0.1.3

- book/src/01_intro.md
- book/src/02_hello_world.md
Hi, I saw the 0.9 announcement, and figured now was as good a time as any to finally learn specs. The original Book PR mentions that the author is not a native English speaker, and that help is welcome. So I figured I'd take a stab at it while I go through the tutorial. Here is my initial pass on the first two chapters. I also noticed that the code at the end of chapter 2 fails to compile so I made a couple of tweaks to fix that. Please let me know if there are any changes you would like me to make. If this is well received, I will try to find some time to work on the other chapters.
> Some grammar changes by a native English speaker

- README.md
- benches/parallel.rs
- benches/world.rs
- book/src/02_hello_world.md
- book/src/03_dispatcher.md
- examples/basic.rs
- examples/full.rs
- examples/serialize.rs
- src/lib.rs
- src/storage/storages.rs
- src/storage/tests.rs
- tests/tests.rs
This PR changes component definitions from:
````rust
impl Component for MyTotallyRadComponent {
type Storage = VecStorage<MyTotallyRadComponent>;
}
````
to
````rust
impl Component for MyTotallyRadComponent {
type Storage = VecStorage<Self>;
}
````
which is shorter for long types and easier to rename. Benefits are especially great when the type has to be repeated multiple times (eg. `FlaggedStorage<MyTotallyRadComponent, VecStorage<MyTotallyRadComponent>>` vs `FlaggedStorage<Self, VecStorage<Self>>`)
It also moves system data destructuring for tuples:
````rust
fn run(&mut self, data: Self::SystemData) {
let (first_component, mut second_component) = data;
````
to
````rust
fn run(&mut self, (first_component, mut second_component): Self::SystemData) {
````
which is shorter and conveys the …
> Change component definitions to use Self and destruct system data tuple in parameter list.

- src/storage/check.rs
Just allows using `Not` with a `CheckStorage`.
> AntiStorage for CheckStorage

- Cargo.toml
- examples/serialize.rs
Cargo can't seem to find the other examples without them being specified now for whatever reason, also cleans up the serialize example by using `required-features` instead of manually doing it in the example.
> Add other examples, required-features for serialize example

- book/src/04_resources.md
Without this:
> error[E0596]: cannot borrow immutable local variable `pos` as mutable
>   --> src/main.rs:52:39
>    |
> 49 |         let (delta, vel, pos) = data;
>    |                          --- consider changing this to `mut pos`
> ...
> 52 |         for (vel, pos) in (&vel, &mut pos).join() {
>    |                                       ^^^ cannot borrow mutably
>
> Make pos mut

- book/src/03_dispatcher.md
If we don't have this:
> thread 'main' panicked at 'No component with the given id. Did you forget to register the component with `World::register::<ComponentName>()`?', /checkout/src/libcore/option.rs:823:4
> Also register Velocity component

- CHANGELOG.md
- src/lib.rs
- src/world.rs
Remove a component lazily without having to borrow its storage. To be used like this:
`let lazy = world.read_resource::<LazyUpdate>();`
`lazy.add_removal::<SomeComponentType>(some_entity);`
> LazyUpdate: lazily insert and remove components, execute closures on world

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/storage/mod.rs
- src/storage/storages.rs
- src/storage/tests.rs
Per #204, `RudyStorage` presently has some caveats:
* Depends on a git checkout of `rudy`
* Depends on Rust nightly
`RudyStorage` therefore lives behind `--features rudy`. Travis now also knows about this feature flag.
> Add RudyStorage

- src/lib.rs
This allows being generic over read and write storages.
> Added MaskedStorage to the re-exports

- Cargo.toml
- src/world.rs
Closes https://github.com/slide-rs/specs/issues/236
Does not bump the specs version number yet. Can be added if ready. Will compile once hibitset has been updated on crates.io.
> Bump crossbeam, hibitset and rayon versions.

- src/storage/mod.rs
- src/storage/storages.rs
Little less scary transformations here, since `mem::transmute` should only be used as a last resort.
> Less scary transform for Join implementations, keeps type safety

- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/storages.rs
Was just getting more difficult to read the file with half of the file being the `FlaggedStorage`, plus it would probably be a better convention for `src/storage/storage.rs` to hold "real" storages like `HashMapStorage` and `DenseVecStorage`, while keeping the "wrapper" storages (`FlaggedStorage`) and "operation" (`AntiStorage`, `CheckStorage`, `RestrictedStorage`) in their own locations.
> Move FlaggedStorage to its own file

- src/common.rs
Fix `Merge` `System`
`Future`s can't be `poll`ed without `Task`.
`Spawn` creates such `Task` and provide API to run inner `Future`
Without this `Merge` will `panic!` when it'll try to call `Future::poll` except if it is trivial custom `Future`
> Fix Merge System

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- src/common.rs
Unfortunately, there has been an error in 0.9.4 which couldn't be detected by CI. This PR ensures this doesn't happen in the future and fixes the error. Additionally, it bumps the version to 0.9.5.
> Fix compilation error in 0.9.4

- Cargo.toml
- src/common.rs
Adds a test to verify that common::Merge works.  Addresses one test box in https://github.com/slide-rs/specs/issues/244
> Add merge test

- Cargo.toml
- examples/cluster_bomb.rs
> Added example that demonstrates LazyUpdate

- .rustfmt.toml
- .travis.yml
- Cargo.toml
- benches/parallel.rs
- benches/storage.rs
- benches/world.rs
- examples/basic.rs
- examples/bitset.rs
- examples/cluster_bomb.rs
- examples/common.rs
- examples/serialize.rs
- src/bitset.rs
- src/common.rs
- src/join.rs
- src/lib.rs
- src/storage/data.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/ser.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world.rs
- tests/tests.rs
The new formatting makes diffs for imports easier to read by using vertical formatting if horizontal doesn't work.
> Format whole codebase

- src/world.rs
> Allow deleting all entities with `World::delete_all`

- src/common.rs
This allows fetching `Errors` without limiting concurrency.
> Use atomic crossbeam structure to add interior mutability to common::Errors

- .rustfmt.toml
- .travis.yml
- benches/world.rs
- examples/cluster_bomb.rs
- examples/common.rs
- examples/full.rs
- src/common.rs
- src/error.rs
- src/lib.rs
- src/world.rs
- tests/tests.rs
Not meant to be merged as is
Fixes #94
> Use Result in several places and solve double deletion problem

- src/join.rs
This was bugging me while reading the docs; this has absolutely zero possible effect, except to maybe make both `rustc` and outside readers slightly more efficient at scanning the code.
> Remove useless lifetime parameter from tuple `impl` heads.

- src/common.rs
This allows using ? for error handling.
> Add Errors::execute method

- .travis.yml
- README.md
This PR adds automatic code coverage testing using `cargo-travis` and `coveralls`.
Note: I cannot add the repo to coveralls as I am not member of the github organization.
> Code coverage using cargo-travis on coveralls.

- CHANGELOG.md
- src/storage/drain.rs
- src/storage/mod.rs
> Add `drain` method to `Storage`

- Cargo.toml
- examples/async.rs
- src/world.rs
I know CI will fail for this, but it won't anymore as soon as merged onto staging by bors.
@kvark if you still want to rename the `serialize` feature, which seems to complicate the `Cargo.toml`, please release a new version after merging this PR and the feature name change. Otherwise, I think we can get 0.10 out after merging only this PR.
> Use new version of shred and add example with `AsyncDispatcher`

- book/src/02_hello_world.md
- book/src/04_resources.md
- book/src/05_storages.md
- book/src/07_parallel_join.md
minor changes in the specs book
> small adjustments in the documentation

- src/error.rs
- src/lib.rs
- src/saveload/de.rs
- src/saveload/details.rs
- src/saveload/marker.rs
- src/saveload/mod.rs
- src/saveload/ser.rs
Add (de)serialization support for entities to specs.
Main parts are:
* `Marker` trait.
`Marker` is used for several purposes:
* Mark which entities should be serialized.
* It contains ID to replace `Entity` stored in `Component`s during serialization process.
* It may contain additional data to be used for tracking owner of the component.
* `MarkerAllocator` trait for allocating `Marker`s, storing `Marker -> Entity` mapping and other stuff.
* `SerializableComponent` trait that is auto implemented by components if they implements `Serialize`, `DeserializeOwned` and `Copy` (later is rather strict, maybe it should be replaced with `Clone` or removed somehow).
Mainly `Component` implements `SerializableComponent` manually when it contains `Entity`.
`Component` should replace `Entity` with …
> Add an ability to save and load entities.

- Cargo.toml
* shorten description because README gets rendered now
* specify `README.md` to make https://crates.io render it
* ask https://docs.rs to build with "common" and "serde" features turned on
> Improve metadata

- book/src/04_resources.md
Sorry, the code was wrong. If you also want to dispatch you'll need to use a scope like so
```rust
let mut world = World::new();
world.add_resource(DeltaTime(0.04));
{
let mut delta = world.write_resource::<DeltaTime>();
delta.0 = 0.02;
// The borrow ends here
}
dispatcher.dispatch(&mut world.res); // so we can borrow from world here again
```
> Replace let delta with let mut delta

- CHANGELOG.md
- benches/parallel.rs
- src/error.rs
- src/lib.rs
- src/storage/mod.rs
- src/storage/tests.rs
- src/world/entity.rs
Fixes #268 
Adds `StorageEntry` to allow for in place insertions, also some other methods for dealing with the occupied and vacant entries, similar to `std`s HashMap Entry.
Still need to add some tests for further verification (I'll do this tomorrow).
> Adds StorageEntry to Storage for convenience

- .travis.yml
- Cargo.toml
- benches/parallel.rs
- examples/saveload.rs
- specs-derive/src/lib.rs
- src/lib.rs
- src/world/mod.rs
Adds a new feature flag `nightly` for unstable, but useful features.
Also adds first feature using the flag which allows clearer panic messages when not adding/registering resources/components.
Examples of new error message when enabled:
```
thread 'main' panicked at 'Component `Pos` was unregistered. Did you forget to register the component with `World::register::<Pos>()`', src\libcore\option.rs:839:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\examples\cluster_bomb.exe` (exit code: 101)
```
```
thread 'main' panicked at 'No resource `specs::saveload::U64MarkerAllocator` exists in the world. Did you forget to add the resource with `World::add_resource::<specs::saveload::U64MarkerAllocator>(...)`', src\libcore\option.rs:839:4 …
```
> Introduce nightly feature

- src/world/mod.rs
Whilst there was already documentation explaining component / resource
IDs, it was easy to skim over and no reference was made by the
read_with_id and write_with_id methods. This made it seem like it
expected an entity ID to search for a component, whereas in reality it's
used for more complex component / resource setups.
This is meant to address #310 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/312)
> Added more documentation to world read / write methods.

- src/join.rs
- src/lib.rs
- src/world/mod.rs
Fixes #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/313)
> Improve Join and Entities docs

- src/storage/flagged.rs
- src/storage/restrict.rs
- src/storage/tests.rs
fixes #295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/306)
> Immutable Restricted Storage

- Cargo.toml
- src/join.rs
- tests/tests.rs
After randomly browsing through [rhusics](https://github.com/Rhuagh/rhusics) I noticed [piece of code](https://github.com/Rhuagh/rhusics/blob/259ff9e4ea61e98919472ea9ac77005177301c1d/src/ecs/collide/systems/spatial_collision.rs#L178) and thought about API that would make it cleaner/more efficient and this is the result.
The code in question after this PR:
```rust
let (left_shape, left_pose, left_next_pose) =
(&shapes, &poses, &next_poses).join().get(left_entity).uwnrap();
let (right_shape, right_pose, right_next_pose) =
(&shapes, &poses, &next_poses).join().get(right_entity).uwnrap();
```
Depends on slide-rs/hibitset#20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/299)
> Adds way of getting components of specific entity

- .travis.yml
- book/src/01_intro.md
Fixes #318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/321)
> Replace specs_website with just the book

- src/lib.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/tests.rs
This shouldn't be allowed in parallel, since that would mean you could have a reader in one thread while you having it mutably in another thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/309)
> RestrictedStorage safety fix

- src/storage/mod.rs
- src/storage/tests.rs
fixes https://github.com/slide-rs/specs/issues/304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/326)
> Replace check with mask, deprecate check

- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/storage/tracked.rs
- src/world/mod.rs
Default-implemented via remove.
Can be overridden for some special components (I'd use this in amethyst renderer).
`AnyStorage::remove` is replaced with `AnyStorage::drop` which doesn't return anything thus avoiding unnecessary boxing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/328)
> Add drop method to UnprotectedStorage trait.

- src/lib.rs
`Resources` should be reexported as it is the only thing that requires average user of `specs` to add `shred` as  direct dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/335)
> Reexport `Resources`

- specs-derive/src/lib.rs
- src/changeset.rs
- src/error.rs
- src/lib.rs
- src/prelude.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/344)
> feat: Add ChangeSet that can be collected into from iterators, and joined over for easy application to components

- src/storage/mod.rs
Just adds a slightly easier and better way to check for the existence of a component on an entity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/374)
> Add contains function to Storage

- benches/storage_cmp.rs
- benches/storage_sparse.rs
- benches/world.rs
- examples/cluster_bomb.rs
- examples/full.rs
- examples/saveload.rs
- examples/track.rs
- src/changeset.rs
- src/common.rs
- src/join.rs
- src/prelude.rs
- src/saveload/marker.rs
- src/storage/data.rs
- src/storage/drain.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/tests.rs
- src/world/entity.rs
- src/world/lazy.rs
- src/world/mod.rs
- src/world/tests.rs
- tests/tests.rs
PR based on conversation here: https://gitter.im/slide-rs/specs?at=5ae0cb975d7286b43a698dbc
Basically these functions now have slightly confusing names, so this PR makes them less ambiguous.  Additionally it re-exports `shred::Resources` to make the `System::setup` function easier to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/375)
> Rename world::read and world::write, re-export shred::Resources

- src/prelude.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/407)
> fix: Reexport ParallelIterator so users don't have to add a rayon dependency directly to use par_join

- src/saveload/de.rs
- src/saveload/ser.rs
The short-term solution for https://github.com/slide-rs/specs/issues/414
I tried adding more, but it looks like 16 is the maximum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/415)
> Increase tuple size for SerializeComponents/DeserializeComponents

- CHANGELOG.md
- Cargo.toml
- src/storage/mod.rs
This is already possible through `Join::open` (although not very ergonomic), so there shouldn't be any soundness issues here. This is useful for using custom storages with additional methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/419)
> Expose the wrapped storage from Read/WriteStorage

- CHANGELOG.md
- Cargo.toml
- src/saveload/marker.rs
- src/saveload/mod.rs
- src/saveload/tests.rs
First one (.marked()) is mostly a copy-paste from EntityBuilder.
Second one fixes what I think is a bug (if I'm using this correctly); on loading my game with `saveload::DeserializeComponents`, it reuses the markers in the saved `.ron` file, but new entities are then created starting from 0, meaning I get duplicate marker .id()'s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/420)
> Add .marked() to LazyBuilder and fix U64MarkerAllocator not updating its index

- src/saveload/marker.rs
- src/world/entity.rs
- src/world/mod.rs
This allows building of entities within a system so long as the necessary Component storages are also available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/424)
> Add EntityResBuilder

- src/saveload/de.rs
- src/saveload/mod.rs
- src/saveload/ser.rs
Exports `IntoSerialize` and `FromDeserialize` to the world, along with documentation. Doc tests pass, but are mostly just simple implementation examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/427)
> Export component-wise saveload traits

- book/src/02_hello_world.md
- book/src/03_dispatcher.md
Hey, @torkleyy asked me to write this up, as I mentioned it on the Gitter (thanks @omni-viral for the help!)
Should I add calls to `maintain` after running systems/dispatchers other places? How is the language used in the chapter?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/451)
> Added maintain calls to initial book examples.

- Cargo.toml
- benches/world.rs
- src/world/entity.rs
This pull request uses a vector to store deleted entities to reduce the complexity of entity allocation to O(1)*.
The maximum memory footprint is 2x the maximum current amount but it can only happen in the worst case and is I believe acceptable for such a use case.
The current approach has the pitfall of often reusing the same entities, hence potentially making their generation quite high. Introducing a VecDequeue instead of the current Vec for the EntityCache could potentially solve this problem (with a cost in memory), so if you believe the change would be worth it I can add it relatively easily. However, this might be unnecessary as 2³¹-1 is the maximum generation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Reduced the complexity of the entity allocator

- Cargo.toml
- src/join.rs
Related issue: https://github.com/slide-rs/specs/issues/358
Adds a generic `MaybeJoin` to all `Join` structures to optionally get a component.
I think we might want to add an `BitSetAll` BitSetLike to hibitset for a more specialized `BitSetNot(BitSet::new())` since I don't like the idea of allocation of some vecs on a join that won't actually be used. Ideally just have a BitSetLike that returns the max usize on all layers.
Dependent on https://github.com/slide-rs/hibitset/pull/36 for optimization (not sure if rust is smart enough to remove the unnecessary Vec allocations.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/455)
> MaybeJoin for possibly existing components

- book/src/03_dispatcher.md
Small change to the dispatcher chapter of the book as discussed in #408. If you run the example code now you'll see the final printed positions include the changes made by `UpdatePos`. This should make it a little easier for someone following along with the examples to verify that their code is working correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/464)
> Book dispatcher chapter - print updated positions

- book/src/02_hello_world.md
With this code so far, following along:
```
extern crate specs;
#[macro_use]
extern crate specs_derive;
use specs::{VecStorage, World};
#[derive(Component, Debug)]
#[storage(VecStorage)]
struct Position {
x: f32,
y: f32
}
#[derive(Component, Debug)]
#[storage(VecStorage)]
struct Velocity {
x: f32,
y: f32,
}
fn main() {
let mut world = World::new();
world.register::<Position>();
let ball = world.create_entity().with(Position { x: 4.0, y: 7.0 }).build();
}
```
one gets this error:
```
error[E0599]: no method named `with` found for type `specs::EntityBuilder<'_>` in the current scope
--> src/main.rs:26:38
|
26 |     let ball = world.create_entity().with(Position { x: 4.0, y: 7.0 }).build();
|                                      ^^^^
|
= help: items from traits can only be used if the trait …
```
> resolve method not defined error

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/storage/mod.rs
- src/world/entity.rs
- src/world/mod.rs
As promised in issue #436, this PR uses `NonZeroU32` in `Generation`. Note this bumps the minimum supported rust version to 1.28 - is this a concern? If so I could put this under a feature flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/447)
> Use non-zero optimization for Generation

- Cargo.toml
- specs-derive/Cargo.toml
- specs-derive/src/lib.rs
"Works on my pc".
So with this you need to have `Component` in scope for the derive to find it and use it. This allows to use it in projects without having to have specs as a hard dependency. <3
Also it might fix the issue with re-exporting the macro, but I didn't test that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/467)
> Switched specs-derive to use Component in scope

- CHANGELOG.md
- src/world/mod.rs
Hello,
`world::World::exec` can be used instead of implementing `world::Bundle`
Related issue: #482 
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/486)
> Deprecate world::Bundle

- CHANGELOG.md
I think we messed up a merge conflict somewhere, not too big of an issue though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/488)
> Duplicate changelog entry?

- specs-derive/Cargo.toml
- specs-derive/src/impl_saveload.rs
- specs-derive/src/lib.rs
- specs-derive/tests/saveload.rs
- src/saveload/de.rs
- src/saveload/mod.rs
- src/saveload/ser.rs
Split from #434
A custom derive for IntoSerialize and FromDeserialize named #[derive(Saveload)]. It may seem odd to derive them together, but after spending significant time trying to do it the normal way (one derive per trait) it became clear that due to the requirement of "proxy" types that fill the IntoSerialize::Data and FromDeserialize::Data fields, it made sense to do it this way or you start getting into attribute hell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/460)
> Saveload custom derive

- Cargo.toml
- src/bitset.rs
- src/join.rs
- src/join/mod.rs
- src/join/par_join.rs
- src/lib.rs
- src/prelude.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/world/entity.rs
This makes it possible to user specs in wasm environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/495)
> Make it possible to disable parallel feature

- CHANGELOG.md
- Cargo.toml
- examples/ordered_track.rs
- examples/track.rs
- src/lib.rs
- src/prelude.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/tests.rs
- src/storage/track.rs
Related issue: https://github.com/amethyst/amethyst/issues/978
Uses a `ComponentEvent` enum instead of 3 separate channels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/489)
> FlaggedStorage changes

- book/src/04_resources.md
- book/src/06_system_data.md
Others have noticed that this section makes many confused by the error message of unimplemented `Default` for the resource. This commit is just a simple cut and paste of the part talking about `Default`. I create this pull request as a placeholder for future rewrite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/496)
> Move discussion on resources deriving Default earier in the book.

- Cargo.toml
- src/storage/mod.rs
I've added `Storage::entities` to allow making extension methods for `Storage` that return `Entity`.
This method is hidden because I'm 100% certain newcomers will be confused by this otherwise. This makes it less visible, yes, but I think that's worth for avoiding this confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/515)
> Allow accessing fetched entities of a `Storage`

- src/storage/entry.rs
- src/storage/mod.rs
- src/storage/tests.rs
This makes it possible to read and insert component at same time inside join iteration.
`Storage::entries` would likely need more docs, however I can not find any really minimal example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/518)
> Add Join-able entries API to Storage

- book/src/12_tracked.md
The documentation for `FlaggedStorage` became out of date with #489. I'm not entirely familiar with this API, so please review to see if my understanding of the changes is correct. I have however made sure that the code sample compiles.
The bit about handling `ComponentEvent::Removed` first is no longer necessary because the events are in the same "channel" and in chronological order, right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/531)
> Fix `FlaggedStorage` docs

- src/world/entity.rs
Fixes #514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/533)
> Fix bug when re-killing Entity after atomic killing followed by alloc

- Cargo.toml
- src/storage/entry.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/543)
> Make Specs compatible with Rust 1.28 again

- src/lib.rs
broken link in https://docs.rs/specs/0.14.3/specs/#the-data: https://docs.rs/specs/0.14.3/specs/struct.World.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/556)
> documentation: fix link to World struct

- book/src/09_parallel_join.md
I was reading online, and spotted a minor typo - the 'el' was omitted in 'parallelization'. Add it back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/560)
> Fix typo in 09_parallel_join.md

- src/storage/generic.rs
- src/storage/tests.rs
Fixes #561
Alternative to #562 . Implements an Option API instead of panicking if the entity is dead
I have no idea how I managed to mess up the branch name.
Closes #562 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/563)
> Optionized get_mut_or_default

- src/bitset.rs
- src/changeset.rs
- src/join/mod.rs
- src/join/par_join.rs
- src/storage/drain.rs
- src/storage/entry.rs
- src/storage/mod.rs
Partial fix for #548 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/566)
> Audit most uses of unsafe

- .gitlab-ci.yml
- README.md
- codecov.yml
- scripts/kcov.sh
* Collect code coverage using `kcov`
* Upload coverage to codecov.io
* Use GitLab CI to do all the work
* Add badge to readme (not yet valid)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/567)
> Add code coverage via GitLab CI

- book/src/06_system_data.md
I'm currently going through the book and noticed a complaint by the compiler here when using `stones.insert(stone, Stone);`, stones should be marked as mutable, or am I missing something?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/577)
> fix: book example variable mutability

- Cargo.toml
- benches/big_or_small.rs
- src/lib.rs
- src/saveload/mod.rs
- src/saveload/tests.rs
- src/saveload/uuid.rs
- src/world/entity.rs
- tests/saveload.rs
Added UuidMarker and UuidMarkerAllocator.
They work the same way their U64 counterparts do.
Added "uuid_entity" feature gate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/584)
> Uuid Marker

- docs/tutorials/src/13_saveload.md
- examples/saveload.rs
- src/saveload/marker.rs
- src/saveload/mod.rs
- src/saveload/tests.rs
- tests/saveload.rs
Fixes #592 
Breaking change: 
`specs::saveload::U64Marker` is replaced with `SimpleMarker<T>`
`specs::saveload::U64MarkerAllocator` is replaced with `SimpleMarkerAllocator<T>`
This change allows multiple instances of SimpleMarker(Allocator) to be used in a single World
`SimpleMarker` is no longer `PartialOrd + Ord` because `derivative` doesn't implement those traits, however they are trivial to implement, up to you to decide whether I should
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/594)
> Replace U64Marker with SimpleMarker<T: ?Sized>

- src/storage/mod.rs
The AntiStorage inner being private prevented any external users of specs to implement an AntiStorage type, which the blanket std::ops::Not implementation requires for allowing negative joins (!&storage). 
This changes the AntiStorage inner to public, allowing external crates to now implement this appropriately
AntiStorage inner is now public
> Changes AntiStorage inner to public

- Cargo.toml
- src/storage/tests.rs
- src/world/comp.rs
`mopa::Any` is less necessary with changes to `std::any::Any`, and `specs` wasn't calling the `mopafy!()` macro for `Component` anyway.
* **n/a** I've added tests for all code changes and additions (where applicable)
* **n/a** I've added a demonstration of the new feature to one or more examples
* **n/a** I've updated the book to reflect my changes
* **n/a** Usage of new public items is shown in the API docs
Nothing in the `specs` repo except the `Component` definition and an associated generic type in a test refer to `Any`, and even then only in type bounds. No tests or examples are affected.
This change breaks any code which specifically needs `trait Component: mopa::Any`, but as far as I can tell [that doesn't work now and hasn't since …
> Remove dependency on mopa crate

- Cargo.toml
- docs/tutorials/src/12_tracked.md
- src/storage/flagged.rs
- src/storage/track.rs
Sometimes you may want to perform some operations on the storage, but you don't want
that these operations produce any event.
You can use the function `storage.set_event_emission(false)` to suppress the event writing for
of any action. When you want to re activate them you can simply call
`storage.set_event_emission(true)`
This change will be used to fix this: https://github.com/amethyst/amethyst/issues/1795
> Start and Stop signal registration for the FlaggedStorage

- docs/tutorials/src/12_tracked.md
Update the `FlaggedStorage` docs to include mutable iteration over `FlaggedStorage`. Update formatting to fit 80-col limit.
* [N/A] I've added tests for all code changes and additions (where applicable)
* [N/A] I've added a demonstration of the new feature to one or more examples
* [N/A] Usage of new public items is shown in the API docs
None
> Update docs for FlaggedStorage and minor reformat.

- Cargo.toml
- src/lib.rs
Updated shred to the last 9.3 version and exposed new `Batch` structures + all other structures needed to create a `Batch` `System`.
> Updated Shred 9.3 and exposed Batch

- .travis.yml
- README.md
- docs/tutorials/src/05_storages.md
- examples/slices.rs
- src/lib.rs
- src/prelude.rs
- src/storage/mod.rs
- src/storage/storages.rs
- src/storage/tests.rs
This PR adds slice access to certain storages. Slices allow the user to bolt on an accelerator framework like OpenCL (#553) for high throughput component processing. My thoughts behind this particular design are https://github.com/slide-rs/specs/issues/553#issuecomment-525099211 and https://github.com/slide-rs/specs/issues/553#issuecomment-525362663.
Non-breaking, strictly additive:
* Add `DenseVecStorage<T>::as_slice() -> &[T]` and `as_mut_slice() -> &mut [T]`.
* Add `VecStorage::unsafe_slice() -> &[T]` and `unsafe_mut_slice() -> &mut [T]`.
* Add `DefaultVecStorage<T>`, which works like `VecStorage<T>`, requires `T: Default`, and provides `as_slice() -> &[T]` and `as_mut_slice() -> &mut [T]`.
* Add `as` or `unsafe` `[_mut]_slice` directly on `Storage` as appropriate.
> Add slice access

- specs-derive/Cargo.toml
- specs-derive/src/impl_saveload.rs
- specs-derive/src/lib.rs
Related #624, #625, #626
Just a simple version bump and small fixes of the changed item and field names.
The `Type` enum has been marked as `__Nonexhaustive` which is the reason for the default match arm addition in https://github.com/Veykril/specs/blob/e114bc59f09dcfb0b1fa16dbcd50e23bec431fd1/specs-derive/src/impl_saveload.rs#L470.
> update syn, quote and proc-macro2 to 1.0

- src/join/mod.rs
- tests/tests.rs
I've added a simple test to make sure `ParJoin` actually works with `MaybeJoin`, but I haven't updated any of the examples.
The test is not terribly important as it wasn't really a question whether it would work or not, the real question is whether it's safe.
> Implement `ParJoin` for `MaybeJoin` if the inner type is `ParJoin`

- Cargo.toml
> Fixes #666

- docs/tutorials/src/05_storages.md
Presumably a copy-paste typo from `DefaultVecStorage`.
> Fix doc typo

- Cargo.toml
Closes #672 
Note : Homepage could be [https://specs.netlify.com](https://specs.netlify.com) instead
> Change homepage to specs.amethyst.rs

- src/join/mod.rs
- src/join/par_join.rs
log is already used in lazy.rs, and the println!s represent their own performance hazard if you really did mean to do an unbounded join.
Additionally, stdio is unavailable or forbidden on some platforms (wasm in the browser, consoles, etc.)
No related issues to mark as fixed.
Presumably already covered by existing tests/docs
None
> Use log::warn! instead of println! for is_unconstrained joins.

- src/storage/mod.rs
This allows users to clone their `ReadStorage` and `WriteStorage` ***fetches*** by adding `Clone` for `Storage<'a, T, D: Clone>`.
> Add clone implementation for Storage

- CHANGELOG.md
- Cargo.toml
- examples/async.rs
- src/world/comp.rs
- src/world/lazy.rs
- src/world/mod.rs
- src/world/tests.rs
- tests/no_parallel.rs
> Remove send+sync requirement if not parallel

- CHANGELOG.md
- Cargo.toml
- src/join/mod.rs
Closes #593 
implement `Clone` for `JoinIter` where possible.
Updates hibitset version as this requires access to `BitIter::clone` and `BitIterAnd::clone`.
This is not a breaking change
> impl Clone for JoinIter

- CHANGELOG.md
- src/storage/entry.rs
- src/storage/tests.rs
Adds a method to StorageEntry:
```rust
/// Inserts a component and returns the old value in case this entry was
/// already occupied.
pub fn replace(self, component: T) -> Option<T> {
match self {
StorageEntry::Occupied(mut occupied) => Some(occupied.insert(component)),
StorageEntry::Vacant(vacant) => {
vacant.insert(component);
None
}
}
}
```
addition of the method `StorageEntry::replace(self, component: T) -> Option<T>`.
This is not a breaking change
> add fn replace to StorageEntry

- .travis.yml
- CHANGELOG.md
- README.md
- docs/tutorials/src/13_saveload.md
- examples/saveload.rs
- specs-derive/src/impl_saveload.rs
- specs-derive/src/lib.rs
- src/error.rs
- src/saveload/mod.rs
- src/saveload/tests.rs
- tests/saveload.rs
* *n/a* I've added tests for all code changes and additions (where applicable)
* *n/a* I've added a demonstration of the new feature to one or more examples
* *n/a* Usage of new public items is shown in the API docs
- Use `#[non_exhaustive]` for `error::Error` instead of `__NonExhaustive` trick. **This is a breaking change, and requires a minimal Rust version of 1.40** (previously 1.38). This notably enables to add new error types without it being a breaking change.
- Change `std::error::Error` implementation of different error types, to use "state of the art" functions instead of deprecated ones.
- Deprecated `NoError` and use `std::convert::Infallible`, and re-export the latter as `NoError` for a smoother transition (maybe we should remove completly). This will also allow a smoother …
> Cleanup error types

- CHANGELOG.md
- Cargo.toml
- docs/tutorials/src/02_hello_world.md
- scripts/build-netlify.sh
- src/lib.rs
* There are currently two distinct *-derive features and it is
uncomfortable to hunt for them.
* They exist mostly due to technical reasons, as they bring two
different crates. The price of the other if one is already present is
relatively low (the cost is by depending on syntax and quote and they
share them).
* This is in the convention of having the `derive` feature flag as serde
and other packages have.
* The original two are still preserved, so users still can enable only
one of them.
Closes #684.
Should I update the examples to use this feature, or leave them be with the current `specs-derive`?
I'm not sure this completely applies. I've updated the note in docs about features, but otherwise left the `specs-derive` as the main suggestion how to use it by users and expect this will be …
> Add derive flag

- src/storage/mod.rs
Fix misleading documentation on `UnprotectedStorage` trait's `drop` method which suggests it has a different implementation than `remove`, while by default it's calling `remove` internally.
> Fix documentation on UnprotectedStorage::drop

- src/saveload/ser.rs
This change modifies the behavior of serialize to calculate the count of items before handing off to the serde serializer. The majority of formats that serde supports require a known count to prefix the data with. (i.e. bincode, msgpack). Most of these will fail serialization immediatly when trying to use them with component serialization.
There is additional overhead from calculating the number of items but the cost appears to be trivial in comparison to the time spent on serialization.
I did not modify serialize_recusive as it would require a much more expensive double-traversal of the data structures inspecting for contained entities.
> Add count to serialize.

- src/storage/mod.rs
This change makes paired storage public to complement the already public restricted storage. The type is not accessible due to the restrict module being private. This means if you want to do anything with paired storage other than treat it as an anonymous type you can't. Given that it does not implement any public traits for storage access, you can't pass it to any other code without wrapping it in another generic type (i.e. putting it in a closure.)
The use case is passing the structure to another function or beyond the original scope it's contained within.
> Expose paired storage.

- specs-derive/src/impl_saveload.rs
- specs-derive/src/lib.rs
- tests/saveload.rs
This change adds additional control to ConvertSaveload derive behavior to customized code generation for the conversion data type. This allows for support of serde traits and non-serializable types. This was previously impossible as the attributes would be identical between the original data type and the conversion data type. This was due to serde traits being invalid on the original data type even if valid on the conversion data type.
Two new helper attributes are added to the ConvertSaveload derive behavior:
1.  'convert_save_load_skip_convert' bypasses calling convert_into/convert_from completly. This is needed as it's not possible to implement a blanket ConvertSaveLoad for 'Clone' types as this behavior is likely not desired and will also create conflicting trait implementation due to …
> Helper attributes for fine grained ConvertSaveload control.

- docs/tutorials/src/07_setup.md
I believe the example intended to be `impl Component for Velocity` rather than `...for Position` as no `Position` struct was present in this example. I also added `#[derive(Default)]` for the `Gravity` struct as it was needed to have an example that would compile. I also gave the `run()` function a valid signature that would allow the example to compile.
> Fix typo substituting Position for Velocity

- docs/tutorials/src/02_hello_world.md
Could not compile with `features = ["derive"]`. Needed it to be `features = ["specs-derive"]`.
> keep version consistent, correct feature flag

- src/world/lazy.rs
- src/world/tests.rs
- src/world/world_ext.rs
None
Before this change if one tried to do `World::system_data<Read<LazyUpdate>>()` within `LazyUpdate::exec` on would get the following error:
```
thread 'main' panicked at 'Already borrowed mutably: InvalidBorrow', /home/delma/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/cell.rs:103:9
stack backtrace:                                                                                                                                              
0: backtrace::backtrace::libunwind::trace                                                             
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1: backtrace::backtrace::trace_unsynchronized                                                         
at …
```
> Allow reentrant laziness

- Cargo.toml
- src/world/lazy.rs
Question: should delete "// TODO: remove as soon as leak is fixed in crossbeam"?
no breaking api changes
> update to crossbeam-queue 0.3

- Cargo.toml
- src/join/mod.rs
- src/lib.rs
- src/saveload/marker.rs
- src/storage/deref_flagged.rs
- src/storage/entry.rs
- src/storage/flagged.rs
- src/storage/generic.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/storages.rs
This PR is extremely experimental and should not be considered a candidate for merging at the current time. It makes use of highly experimental nightly Rust features and introduces breaking API changes. I am opening it here to make others aware of it and encourage discussion about it.
This PR makes significant changes to the storage traits and introduces, via GATs (Generic Associated Types) the ability for storages to provide a wrapper type to systems that access them instead of simple mutable references.
This has the advantage that it allows storages to detect usage of the wrapper more precisely via the `Deref`/`DerefMut` traits. I have used this fact to implement a significantly more precise version of `FlaggedStorage` known as `DerefFlaggedStorage` that only emits component …
> Added DerefFlaggedStorage to allow for more precise flagged storage events

- benches/world.rs
This MR adds a simple benchmark for how long it takes to fetch storages. I find this useful for potential decisions on when to optimize code using `specs` to reuse fetched storages instead of grabbing them as needed.
No API changes.
> Add benchmark for storage fetching

- src/storage/entry.rs
In this function you use the unsafe keyword for one safe expression.
We need to mark unsafe operations more precisely using unsafe keyword. Keeping unsafe blocks small can bring many benefits. For example, when mistakes happen, we can locate any errors related to memory safety  within an unsafe block. This is the balance between Safe and Unsafe Rust. The separation is designed to make using Safe Rust as ergonomic as possible, but requires extra effort and care when writing Unsafe Rust. 
Hope this PR can help you.
Best regards.
**References**
https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html 
https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html
> The scope of the unsafe block can be appropriately reduced

- Cargo.toml
- examples/saveload.rs
- src/saveload/tests.rs
> update all depdnencies including hashbrown

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- deny.toml
- src/world/entity.rs
- src/world/world_ext.rs
- tests/tests.rs
* ~~[ ] I've added a demonstration of the new feature to one or more examples~~
* ~~[ ] I've updated the book to reflect my changes~~
* ~~[ ] Usage of new public items is shown in the API docs~~
`WorldExt::delete_entities` method now includes the index of the entity with the wrong generation to indicate to the user where it stopped (since entities after that are not deleted).
> Delete components after killing entities to avoid clearing components when the entity has the wrong generation

- Cargo.toml
- docs/tutorials/src/06_system_data.md
- examples/full.rs
- miri.sh
- src/lib.rs
Also hide optional uuid dep from features since it is enabled indirectly via `uuid_entity` feature (and not intended to be enabled directly)
This is a breaking change.
The `SystemData` derive now requires `shred` to be in scope rather than all the individual types that the derive needs.
> Update shred to 0.16.0
