- examples/basic.rs
- src/lib.rs
- src/storage.rs
Fixes #5 
Partially addresses #4 
Partially implements #3
> Generational indices

- Cargo.toml
- examples/basic.rs
- src/lib.rs
- src/storage.rs
Fixes #3 
Adds https://github.com/chris-morgan/mopa as a dependency
cc @chris-morgan
> Storage base trait

- Cargo.toml
- src/lib.rs
- src/storage.rs
In my benchmarks this is twice as fast as the Sip hasher fore only 5 extra lines.
> use fnv hasher

- examples/basic.rs
- src/lib.rs
> Dynamic entity insertion/removal

- src/lib.rs
- tests/tests.rs
This probably should have been part of #17
> Panic if a task Panics

- examples/basic.rs
- src/lib.rs
- src/world.rs
Also added an error message for unregistered types and fixed several clippy warnings like elided lifetimes, I hope noone is against that.
> Added comments to example

- README.md
- examples/basic.rs
- src/lib.rs
- src/world.rs
Added Gitter badge, link to benchmark and added an example for entities creation.
> Readme update

- .travis.yml
- Cargo.toml
- README.md
- examples/basic.rs
- src/lib.rs
- tests/tests.rs
> Migration PR

- src/lib.rs
- src/world.rs
> Removal of FetchArg

- src/bitset.rs
- src/join.rs
- src/lib.rs
- src/storage.rs
> AntiStorage

- Cargo.toml
- examples/basic.rs
- src/world.rs
This is a pretty small change, it add a concept of `Resources` to `specs`. A Resource works like a component in how it is synchronised with systems, but itself does not contain any entities.
> Added resources to the world object

- Cargo.toml
- examples/basic.rs
- src/lib.rs
- src/world.rs
- tests/tests.rs
> Safer instant entity creation

- src/lib.rs
- src/storage.rs
- src/world.rs
- tests/tests.rs
Fixes #61 , fixes #60
cc @malleusinferni
> Fixed has_gen() and World access

- src/world.rs
This is embarrassing since I wrote this.
> Fix for #65

- .travis.yml
- Cargo.toml
- examples/basic.rs
- src/lib.rs
- src/planner.rs
- tests/tests.rs
[My own use case has found that the sequencing of components is essentially linear](https://github.com/serprex/rg/commit/f6cb0bf8aa2797eef8758ec8caae44ce6605e966)
> Put planner with threadpool/pulse dependencies behind feature

- src/storage.rs
This is just something I saw while working on a fix for #73 (which I was beaten to). This is an extremely minor patch that makes the intent of `insert` more clear.
> Fix uninitialized memory read in StorageVec::insert

- Cargo.toml
- examples/basic.rs
- src/lib.rs
- src/planner.rs
- tests/tests.rs
* Use the number of cpus as pool size
* Allows sharing the thread pool
> Add more constructors

- .travis.yml
- Cargo.toml
- src/gate.rs
- src/lib.rs
- src/planner.rs
- src/storage.rs
- src/world.rs
- tests/tests.rs
Fixes #53
Has "ticket" feature that is enabled by default.
Embrace parallel execution!
> Ticketed locks

- src/planner.rs
- tests/tests.rs
> Improving fetch usage

- src/lib.rs
- src/storage.rs
> Add: BTreeStorage

- .travis.yml
- benches/benches.rs
> Fix benchmarks and compile them on Travis

- Cargo.toml
- src/bitset.rs
- src/join.rs
- src/lib.rs
- src/planner.rs
- src/storage.rs
- src/world.rs
* rustfmt
* reorder imports
* newlines between methods
* replace `*` import from planner
> Crate polishing

- examples/basic.rs
- src/lib.rs
- src/storage.rs
> Dense vector storage

- Cargo.toml
- src/storage/mod.rs
Updates to the latest serde version.
> Update to serde 1.0

- Cargo.toml
- benches/parallel.rs
- examples/basic.rs
- examples/full.rs
- examples/serialize.rs
- src/lib.rs
- src/storage/mod.rs
- src/storage/tests.rs
- src/world.rs
- tests/tests.rs
* Removes context
* Rename System::work to run
* Change component / resource ids to usize
> Update to latest shred

- src/lib.rs
- src/storage/mod.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world.rs
> Release Debug requirement and improve crate-level docs

- Cargo.toml
- src/storage/mod.rs
- src/world.rs
> Follow API guidelines a bit more

- Cargo.toml
@WaDelma Just rebase onto master after this PR is merged.
> Use hibitset 0.1.2

- book/src/05_storages.md
- book/src/06_system_data.md
- book/src/07_rendering.md
- book/src/SUMMARY.md
* Clarify wording in storages chapter
* Add [DRAFT] to SystemData
* Add (rather small) Rendering chapter
> Improve book

- src/storage/check.rs
- src/storage/data.rs
- src/storage/mod.rs
- src/storage/ser.rs
- src/storage/storages.rs
- src/storage/tests.rs
- tests/tests.rs
Split up storage module to make it easier to understand.
> Storage module reorganization

- Cargo.toml
It's finally here :tada: 
Thanks, especially,
* @WaDelma 
* @Aceeri 
* @Object905
for contributing and reviewing!
> Publish 0.9.0

- src/lib.rs
I guess it is work in progress since you already implemented the dispatch_seq. it compiles to wasm & works for me after this fix.
> disable AsyncDispatcher use for emscripten

- Cargo.toml
- examples/common.rs
- src/common.rs
- src/lib.rs
cc @ebkalderon @Xaeroxe
Will be used by https://github.com/amethyst/amethyst/pull/244
> Integrate futures

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/world.rs
> Add LazyInsertions

- benches/storage.rs
- src/lib.rs
Just sets up some basic benchmarks for different storages.
> Storage benchmarks

- src/storage/check.rs
- src/storage/tests.rs
> ParJoin implementation for CheckStorage

- src/common.rs
This ports a bug fix ( #243 ) by @omni-viral
back to 0.9
This includes the following commits:
* Poll on Spawn, not on Future
* Do not require Spawn to be Sync
* Fix typo
* Get rid of RefCell
> Backport #243 to 0.9

- Cargo.toml
- benches/parallel.rs
- benches/storage.rs
- benches/world.rs
- examples/cluster_bomb.rs
- examples/full.rs
- src/common.rs
- src/join.rs
- src/lib.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world.rs
- tests/tests.rs
* Replace UnprotectedStorage::new with Default::default
* Add derivative crate
* Derive Default for many types
* Fix numbers, initialization syntax, warnings, ..
* Run clippy and implement most suggestions
* Fix grammar mistakes
> Fix many stylistic issues

- .travis.yml
- benches/storage.rs
- book/src/05_storages.md
- src/lib.rs
> Add benchmark for RudyStorage

- src/world.rs
Partially addresses #145 
Partially addresses #244 
Fixes #202
> Improve docs in world module

- src/storage/mod.rs
- src/storage/storages.rs
- src/storage/tests.rs
> Fix insertion into occupied `NullStorage` entry

- src/world.rs
This PR permits recursive worlds.
> impl Component for World

- Cargo.toml
- src/common.rs
- src/lib.rs
- src/world.rs
> Add examples and explanations to several item docs

- src/storage/tracked.rs
- src/world/mod.rs
This addresses one concern @kvark mentioned in a previous review.
> Make entity building safe by default

- CHANGELOG.md
- src/bitset.rs
Also adds a bunch of the missing changes to the change log.
> Allow consuming of BitSets, adds AtomicBitset to Joinable bitsets.

- book/src/06_system_data.md
- src/storage/data.rs
- src/world/mod.rs
Fixes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/322)
> Document aliasing rules for resources

- src/lib.rs
- src/world/entity.rs
- src/world/lazy.rs
- src/world/mod.rs
Fixes #319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/320)
> Add `LazyBuilder`

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/323)
> Update link to the book

- Cargo.toml
- src/join.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/329)
> Update to hibitset 0.4.1

- specs-derive/Cargo.toml
- specs-derive/src/lib.rs
- src/lib.rs
Not meant to merge yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/343)
> Upgrade syn and quote, rename component attrib to storage

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/345)
> Add lines of code badge

- Cargo.toml
- README.md
- benches/parallel.rs
- book/src/03_dispatcher.md
- book/src/09_rendering.md
- examples/async.rs
- examples/basic.rs
- examples/cluster_bomb.rs
- examples/common.rs
- examples/full.rs
- examples/serialize.rs
- examples/track.rs
- src/common.rs
- src/lib.rs
- src/storage/data.rs
- src/storage/flagged.rs
- src/storage/tests.rs
- src/world/lazy.rs
- src/world/mod.rs
- tests/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/346)
> Upgrade shred

- book/src/01_intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/350)
> Remove duplicated reference to docs.rs

- book/src/08_parallel_join.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/356)
> Improve parallel join chapter in the book.

- Cargo.toml
- book/src/01_intro.md
- src/join.rs
This will need new versions of hibitset and shred too, so they'll all agree on rayon 1.0.
cc amethyst/amethyst#579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/352)
> Update to rayon 1.0

- Cargo.toml
- benches/parallel.rs
- benches/storage_cmp.rs
- benches/storage_sparse.rs
- examples/cluster_bomb.rs
- examples/serialize.rs
- src/common.rs
- src/prelude.rs
- src/saveload/de.rs
- src/saveload/marker.rs
- src/saveload/ser.rs
- src/storage/data.rs
- src/storage/restrict.rs
- src/world/entity.rs
- src/world/lazy.rs
- src/world/mod.rs
- tests/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/367)
> refactor: Update to shred 0.7

- src/prelude.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/368)
> fix: Expose ReadExpect/WriteExpect

- Cargo.toml
- benches/storage_cmp.rs
- benches/storage_sparse.rs
- examples/cluster_bomb.rs
- examples/common.rs
- specs-derive/src/lib.rs
- src/common.rs
- src/error.rs
- src/join.rs
- src/lib.rs
- src/saveload/de.rs
- src/saveload/marker.rs
- src/saveload/ser.rs
- src/storage/data.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/ser.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world/entity.rs
- src/world/mod.rs
- tests/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/369)
> Upgrade to latest shred version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/371)
> Bump version to 0.11-alpha1

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/373)
> Update changelog to 0.11 alpha

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/377)
> Bump to alpha3

- src/lib.rs
- src/storage/data.rs
- src/world/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/379)
> Add `World::{exec, setup}`

- src/saveload/de.rs
- src/saveload/mod.rs
- src/saveload/ser.rs
- src/storage/generic.rs
- src/storage/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/380)
> fix: Move generic storage wrappers to a better place, and expose them

- Cargo.toml
- examples/cluster_bomb.rs
- examples/common.rs
- examples/saveload.rs
- specs-derive/src/lib.rs
- src/common.rs
- src/error.rs
- src/join.rs
- src/saveload/marker.rs
- src/storage/data.rs
- src/storage/flagged.rs
- src/storage/ser.rs
- src/world/entity.rs
- src/world/mod.rs
- tests/tests.rs
Fixes #383.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/384)
> fix: ReadStorage/WriteStorage don't register storages in MetaTable during setup

- book/src/02_hello_world.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/387)
> Updated book to use storage instead of component (specs-derive)

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/390)
> Update shrev to rewritten version

- Cargo.toml
- examples/full.rs
- src/common.rs
- src/error.rs
- src/lib.rs
- src/saveload/marker.rs
- src/storage/data.rs
- src/storage/generic.rs
- src/storage/mod.rs
- src/storage/ser.rs
- src/storage/tests.rs
- src/world/entity.rs
- src/world/lazy.rs
- src/world/mod.rs
- src/world/tests.rs
- tests/tests.rs
Fixes #385
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/386)
> Add must_use to InsertResult

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/391)
> Update to release version of shrev

- CHANGELOG.md
- src/bitset.rs
- src/changeset.rs
- src/common.rs
- src/error.rs
- src/join.rs
- src/lib.rs
- src/storage/mod.rs
- src/world/mod.rs
fixes #393
fixes #388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/394)
> Copy-paste prelude into root, fix #393, fix #388

- book/src/02_hello_world.md
- book/src/11_advanced_component.md
- book/src/SUMMARY.md
Fixes #334 
Fixes #332 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/395)
> book: Add a chapter about advanced component strategies

- src/saveload/ser.rs
- src/storage/mod.rs
- src/world/mod.rs
Fixes #364.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/401)
> fix: Add ParJoin for AntiStorage

- book/src/11_advanced_component.md
- book/src/12_tracked.md
- book/src/13_troubleshooting.md
- book/src/SUMMARY.md
Fixes #333, #331.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/400)
> book: Improve the book

- src/lib.rs
- src/prelude.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/402)
> Added NullStorage to prelude

- book/src/07_setup.md
- book/src/09_parallel_join.md
- book/src/10_rendering.md
- book/src/11_advanced_component.md
- book/src/12_tracked.md
Here's a collection of very minor changes, including at least one Oxford comma.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/403)
> Book: Mostly pedantic punctuation fixes.

- Cargo.toml
- src/lib.rs
- src/prelude.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/405)
> fix: Update shred after SystemData refactor

- src/lib.rs
- src/prelude.rs
closes #404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/406)
> Fix publicity of HashMapStorage

- book/book.toml
- book/src/SUMMARY.md
Fixes #410 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/411)
> Make the book build again

- book/src/03_dispatcher.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/417)
> Type, not binding

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/418)
> Bump version to 0.11.1, update log

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/425)
> Bump version and add to changelog

- Cargo.toml
- benches/parallel.rs
- benches/storage_cmp.rs
- benches/storage_sparse.rs
- benches/world.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/432)
> Fix bench warnings and disable autobenches

- CHANGELOG.md
- examples/common.rs
- specs-derive/src/lib.rs
- src/bitset.rs
- src/changeset.rs
- src/common.rs
- src/join.rs
- src/lib.rs
- src/prelude.rs
- src/saveload/marker.rs
- src/saveload/tests.rs
- src/storage/drain.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/track.rs
- src/world/entity.rs
- src/world/mod.rs
Fixes #428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/429)
> Format and mark unsafe functions as such

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/435)
> Propagate nightly feature to shred

- CHANGELOG.md
- src/world/lazy.rs
- src/world/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/433)
> Allow adding resources from a system

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/439)
> Bump Specs to 0.12

- src/world/entity.rs
- src/world/lazy.rs
- src/world/mod.rs
Fixes #442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/443)
> Add must use to builders

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/449)
> Bump to 0.12.1

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/458)
> Bump version to 0.12.2

- specs-derive/Cargo.toml
Fixes #453
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/459)
> Fix repo link of specs-derive and bump version

- CHANGELOG.md
- Cargo.toml
- examples/cluster_bomb.rs
- examples/full.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/466)
> Update deps, examples and bump version

- book/src/07_setup.md
Minor fix,
fixes #473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/474)
> Use `fetch_mut` in book chapter 7, `setup`

- CHANGELOG.md
- benches/storage_cmp.rs
- book/src/06_system_data.md
- book/src/08_join.md
- book/src/11_advanced_component.md
- examples/cluster_bomb.rs
- examples/full.rs
- examples/track.rs
- src/common.rs
- src/join.rs
- src/saveload/marker.rs
- src/saveload/ser.rs
- src/saveload/tests.rs
- src/storage/drain.rs
- src/storage/flagged.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/tests.rs
- src/world/entity.rs
- src/world/mod.rs
- tests/tests.rs
So we can finally get rid of the confusion with `&*entities` and such.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/472)
> Implement Join for Fetch/Read/Write resources

- src/changeset.rs
- src/saveload/de.rs
- src/saveload/ser.rs
- src/world/entity.rs
- src/world/lazy.rs
Some unused lifetimes and unnecessary references (because of `Clone`/`Copy` implementations), etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/476)
> Clippy-based polishing

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/478)
> Fix changelogs, adds unreleased to 0.12.3 notes

- src/storage/mod.rs
- src/world/lazy.rs
- src/world/mod.rs
Fixes #475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/477)
> Insertion documentation

- book/src/11_advanced_component.md
A few of these were missing in the book, this adds them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/481)
> Add missing joins

- CHANGELOG.md
- book/src/07_setup.md
- examples/basic.rs
- examples/cluster_bomb.rs
- examples/full.rs
- examples/track.rs
Hello,
This adds a few examples to the setup chapter on what should be (?) the preferred way of adding Components and Resources, it also updates the examples to follow that methodology
Closes issue #482 
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/487)
> Provide examples of using `setup()` in Book and examples

- specs-derive/Cargo.toml
- tests/saveload.rs
<3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/501)
> Removed cyclic dependency from specs-derive

- specs-derive/src/impl_saveload.rs
- src/saveload/de.rs
- src/saveload/mod.rs
- src/saveload/ser.rs
See #503.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/504)
> renamed ConvertSaveload::into/from to convert_into/convert_from

- CHANGELOG.md
- Cargo.toml
- README.md
- book/src/02_hello_world.md
- examples/ordered_track.rs
- examples/track.rs
- src/world/mod.rs
- src/world/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/506)
> Bump versions

- book/src/04_resources.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/507)
> Add a derive Default attribute for a resource in the book

- src/world/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/511)
> add doc to EntityBuilder to show entity creation with optional components

- src/storage/storages.rs
Fixes #484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/527)
> Clarify dense property of DenseVecStorage

- src/storage/restrict.rs
Fixes #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/528)
> Fix grammar of RestrictedStorage docs

- bors.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/530)
> Remove Reviewable garbage from merge commits

- Cargo.toml
- src/storage/mod.rs
Fixes #517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/534)
> Add Storage::count and Storage::is_empty

- CHANGELOG.md
- Cargo.toml
- specs-derive/Cargo.toml
Fixes #521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/535)
> Update Changelog, bump versions

- src/saveload/marker.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/539)
> Fix doctest warning

- README.md
Fixes #421
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/540)
> Document public dependencies

- .travis.yml
- Cargo.toml
- src/world/lazy.rs
Related #551 #549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/552)
> Update crossbeam and cgmath dependencies

- book/src/08_join.md
Minor fix to documentation since I've spent some time figuring this one out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/554)
> Joining entities requires a *

- book/src/02_hello_world.md
- book/src/03_dispatcher.md
- book/src/06_system_data.md
- book/src/08_join.md
I fixed a few minor inconsistencies in the book that I noticed while reading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/564)
> Fix small inconsistencies in book

- .gitlab-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/569)
> Fix GitLab CI code coverage

- .gitlab-ci.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/570)
> Some more fixes to code coverage

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/576)
> Fix elif in .travis.yml

- Cargo.toml
- benches/big_or_small.rs
- src/world/entity.rs
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/583)
> Big VS Small component benchmarks.

- docs/website/content/pages/docs.md
- scripts/build-netlify.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/587)
> Book path fixes, fix link to tutorials

- src/saveload/ser.rs
Fixes #590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/591)
> Fix SerializeComponents::serialize_recursive by removing extraneous generic parameter

- Cargo.toml
- src/bitset.rs
Fixes #598 
----
Merging this PR requires slide-rs/hibitset#45 to be merged in some release. Then this PR wouldn't require a `Cargo.toml` change.
I didn't actually do the checklist. Are any of the items required for this change?
> Implement Join on BitSetLike trait object

- docs/website/content/pages/docs.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/specs/597)
> Fix API docs link

- README.md
> Update README.md - fix travis link

- README.md
Update book link to the correct location in README,
> Fix book link in README.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .travis.yml
- CHANGELOG.md
- benches/storage_sparse.rs
- docs/tutorials/src/04_resources.md
- docs/tutorials/src/06_system_data.md
- docs/tutorials/src/08_join.md
- docs/tutorials/src/11_advanced_component.md
- docs/tutorials/src/14_troubleshooting.md
- examples/full.rs
- src/bitset.rs
- src/changeset.rs
- src/saveload/marker.rs
- src/saveload/uuid.rs
- src/storage/entry.rs
- src/world/entity.rs
- src/world/lazy.rs
- src/world/world_ext.rs
They are all simple changes, none of the boxes apply.
> minor nitpicks

- Cargo.toml
- src/changeset.rs
- src/saveload/marker.rs
- src/storage/mod.rs
- src/storage/storages.rs
- src/world/lazy.rs
* n/a I've added tests for all code changes and additions (where applicable)
* n/a I've added a demonstration of the new feature to one or more examples
* n/a I've updated the book to reflect my changes
* n/a Usage of new public items is shown in the API docs
Derivative is a quite costly dependence in term of build time, so we can remove it at small cost
> Remove derivative dependency

- .travis.yml
- Cargo.toml
- README.md
- docs/tutorials/src/14_troubleshooting.md
- scripts/build-netlify.sh
- src/lib.rs
Note : it bumps minimal Rust version to 1.38
> Update shred version

- Cargo.toml
afaik we export hashbrown, so we break API here
> update dependencies: hashbrown and rayon

- Cargo.toml
- benches/parallel.rs
- benches/storage_cmp.rs
- benches/world.rs
- src/join/mod.rs
- src/lib.rs
- src/saveload/marker.rs
- src/storage/tests.rs
- tests/tests.rs
merge this after https://github.com/amethyst/shred/pull/207 got merged.
It updates smallvec due to an security issue.
It also fixes some clippy in some test/bench files
dependencies
> update dependencies and update specs to fix a security issue

- src/storage/mod.rs
> Reveal FlaggedAccessMut in public context

- docs/tutorials/src/06_system_data.md
* I've added tests for all code changes and additions (where applicable)
N/A It's a documentation update
* I've added a demonstration of the new feature to one or more examples
N/A I added an example to an existing feature
* I've updated the book to reflect my changes
N/A That's all this commit does
* Usage of new public items is shown in the API docs
N/A
None
This is just a minor change to the [specs book ](https://specs.amethyst.rs/docs/tutorials/01_intro.html). I can further refine this change if it's not up to the standards here or if we want to make it more clear but I personally believe the changes to be sufficient.
I couldn't find documentation on how to do this in the book itself, or really anywhere else on the internet. It probably exists somewhere but I think searching for a few …
> Added an extra example to the sixth chapter in the book

- .github/workflows/ci.yml
- .rustfmt.toml
- benches/world.rs
- examples/saveload.rs
- specs-derive/src/impl_saveload.rs
- src/join/mod.rs
- src/lib.rs
- src/saveload/marker.rs
- src/saveload/mod.rs
- src/saveload/tests.rs
- src/storage/deref_flagged.rs
- src/storage/flagged.rs
- src/storage/generic.rs
- src/storage/mod.rs
- src/storage/restrict.rs
- src/storage/storages.rs
- src/storage/tests.rs
- src/world/lazy.rs
- src/world/mod.rs
- src/world/world_ext.rs
- tests/saveload.rs
> Enable fmt

- specs-derive/LICENSE-APACHE
- specs-derive/LICENSE-MIT
Fixes https://github.com/amethyst/specs/issues/735
> Add missing licenses to specs-derive crate root

- CHANGELOG.md
- Cargo.toml
Include examples and benchmarks when publishing to fix error when verifying Cargo.toml, also fix link in changelog
> Minor fixes for releasing 0.19

- CHANGELOG.md
- Cargo.toml
Bumps version and adds label in changelog
> Prepare for 0.20 release

- README.md
Sorry, I messed up in 25f5c61 ( #777 )  and accidentally changed the wrong links.
Because it was already merged I decided against amending the original commit and created this new one.
> Change crate io / rs links

- Cargo.toml
Note: aHash is a patch version higher than #770 should not have the license issues
> update aHash and dev dependencies
